vich_uploader:
    db_driver: orm

    mappings:
        users_image:
            uri_prefix: /img/users
            upload_destination: '%kernel.project_dir%/public/img/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        ads_image:
            uri_prefix: /img/ads
            upload_destination: '%kernel.project_dir%/public/img/ads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
